### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by Ironholds** [wikimedia-research/WMUtils#3]
Almost no functionality has examples.

**Comment by sshtomar** [comment]
Hi @Ironholds,
I can work on documenting this. I know this is for Wikimedia's internal usage. I have used some of the libraries mentioned here for a Session reconstrution task.
Let me know where can I start ?

**Comment by Ironholds** [comment]
Hey @Autodidact24 

This package is a legacy one and hasn't been maintained for...a long while. If you've been using the session reconstruction stuff, reconstructr is the way to go. If there's other stuff you're interested in doing that lives in this package it's almost certainly been ported somewhere else by now - lemme know what it is and I can point you to it :)

**Comment by sshtomar** [comment]
@Ironholds Thanks for the response. I would just like to contribute in general. Let me know if there's any data science (very broad description) project :), I can contribute to. I worked on the session reconstruction task you posted [here](https://github.com/wikimedia-research/search_task), some time back. Found that to be very interesting :)
